### PR TITLE
Handle only the relevant events to prevent continuous crash

### PR DESCRIPTION
**Pull request by alok87**
**What?**
Typecast the event object only when the event is relevant.

Fixes https://github.com/ksync/ksync/issues/334

### CODE REVIEW

**Comment by alok87** [comment]
@grampelberg 
Now, after making ksync handle only relevant events this has issue got fixed, its not crashing  👍 
We can take this PR live. Please check.

**Comment by grampelberg** [comment]
@alok87 it sounds like this doesn't fix it for you? Seems like a reasonable change either way.

**Comment by grampelberg** [comment]
@alok87 please sign your commits so that I can merge this.

**Comment by alok87** [comment]
@grampelberg There were 2 issues:
- one was continous failure because of this and after this failure syncthing process was not cleaned up so the port `:8384` was still occupied so the next restart by our ksync wrapper(`practl sync` which runs ksync in while true loop) was failing. So doing this stops this failure and makes it not fail for not relevant events. I will debug next why we are getting 500s for some of the events.
- second was a repeated 1min40sec failure that happens as mentioned in this https://github.com/ksync/ksync/issues/337. Still finding the root cause.

have pushed the signed commit

**Comment by timfallmk** [comment]
@alok87 I'm trying to catch up here, so let me see if I'm understanding correctly. When we do an event request, and for some reason the cluster errors out, the returned event doesn't match type and the process fails. Is that right?

If I'm understanding that correctly this change might "fix" it in that it doesn't crash in this case, but it also won't catch any errors. Let me think about this a little bit and see if we can handle it gracefully.

**Comment by alok87** [comment]
@timfallmk out of the two issues i mentioned above
1) In the first (for the issue #334) the process was exiting without clearning of syncthing process. But after this fix it is not a problem anymore.
2) In the second, the exit is gracefull already, no dangling syncthing process is left behind.

**Comment by timfallmk** [comment]
Got it @alok87 . I read it wrong. Looked like you weren't handling _any_ errors from the events stream, but I see what's going on now. Merged and released in https://github.com/ksync/ksync/releases/tag/0.4.4

**Comment by alok87** [comment]
thanks @timfallmk

**Pull request merged**
