### PR TITLE
Switch to use Go modules from dep

### PR DESCRIPTION
**Pull request by alok87**
Moving to use Go modules as being discussed here #253 

## How was the migration done?
```
cd ~/code
git clone https://github.com/vapor-ware/ksync && cd ksync
git checkout -b gomod
export GO111MODULE=on
go mod init github.com/vapor-ware/ksync
go mod tidy
rm -f Gopkg.lock
rm -f Gopkg.toml
git add .
git commit
git push
```

## Tests
- Build is working
```
$ make build-cmd
```
- ksync is working after this tested it with a remote k8s cluster.

### CODE REVIEW

**Comment by alok87** [comment]
Currently stuck at make build failing at below.

```
$ make build
protoc proto/*.proto --go_out=plugins=grpc:pkg
GOBIN=/Users/alok87/code/practo/ksync/bin go install  \
		-tags '' \
		-ldflags '-w -X github.com/vapor-ware/ksync/pkg/ksync.GitCommit=1042504 -X github.com/vapor-ware/ksync/pkg/ksync.BuildDate= -X github.com/vapor-ware/ksync/pkg/ksync.VersionString=corrupted-version -X github.com/vapor-ware/ksync/pkg/ksync.GoVersion=go1.12.1 -X github.com/vapor-ware/ksync/pkg/ksync.GitTag= -X github.com/vapor-ware/ksync/pkg/radar.GitCommit=1042504 -X github.com/vapor-ware/ksync/pkg/radar.BuildDate= -X github.com/vapor-ware/ksync/pkg/radar.VersionString=corrupted-version -X github.com/vapor-ware/ksync/pkg/radar.GoVersion=go1.12.1 -X github.com/vapor-ware/ksync/pkg/radar.GitTag= ' \
		github.com/vapor-ware/ksync/cmd/ksync
# github.com/vapor-ware/ksync/pkg/proto
pkg/proto/ksync.pb.go:26:11: undefined: proto.ProtoPackageIsVersion3
pkg/proto/radar.pb.go:26:11: undefined: proto.ProtoPackageIsVersion3
make: *** [build-cmd] Error 2
```

**Comment by timfallmk** [comment]
You may want to set this as a draft PR until you're ready for review

**Comment by alok87** [comment]
Its working locally, tested it. Please review

**Comment by grampelberg** [comment]
You'll need to get CI working again before this can merge. Looks like there needs to be some tweaks to how it is being run.

**Comment by grampelberg** [comment]
I cherry picked this into another branch for merge, as I can't fix the gopkg.lock issue myself.

**Pull request closed without merging**
